### PR TITLE
Added logging with levels.

### PR DESCRIPTION
**Pull request by cappe987**
Issue #50: reimplement logging.
- Initialize it by setting the logging level you want displayed. 
- Create Log outputs with a level for when it should be displayed.
- Set file output.

I didn't write any logging in the copying part since that will be affected by the Redis Pipeline change.

I set it to 3 output levels because I thought that seemed reasonable. Another option could be to have different categories, like `Reads`, `Writes`, `Actions`, etc.

### CODE REVIEW

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
For now, just make `logging.go` a file within `utils`, no need for a separate directory (package) yet (though once utils grows enough I will do that). 

Logging should be optional, and previously, was represented as a boolean key in the YAML config file (as `log`) as well as a field (`Log`) in the `Config` struct. I like your implementation of logging levels, but wondering if using ints to represent them over string args is less user-friendly.

**Comment by cappe987** [comment]
Ah right. I forgot to add it to the config. I'll fix that.

I am using ints to represent levels because that's the natural way to represent levels. I used a "enum" to avoid accidentally inputting invalid logging levels (although Go doesn't support real enums so it's not completely safe anyways). Should we use strings like "one", "two", "three"? I also restricted it to 3 levels, which we could change or just remove any restriction on it. 

As for putting it in its own dir/package is because I wanted it to have its own package. Not just be `utils.` like everything else. To be honest, I want to just completely change the name `utils`. Not everything can be considered "utilities". Give it proper package names. I'd personally use `src` or `lib`, but I saw Go likes to use `pkg` for the main code folder. Then use subfolders for any files so they can have packages that actually correspond to what they are.
```
pkg
  |--convert
  |   |--db.go
  |--logging
      |--logging.go
  |--utils
      |--validator.go
```
Even `validator.go` could have a proper package name but I couldn't think of one right now. Generally, you want to avoid having a bunch of `utils` functions. Try to find a proper name or place for them. Otherwise it becomes a loose collection of things that have nothing in common.

**Comment by DGKSK8LIFE** [comment]
> Ah right. I forgot to add it to the config. I'll fix that.
> 
> I am using ints to represent levels because that's the natural way to represent levels. I used a "enum" to avoid accidentally inputting invalid logging levels (although Go doesn't support real enums so it's not completely safe anyways). Should we use strings like "one", "two", "three"? I also restricted it to 3 levels, which we could change or just remove any restriction on it.
> 
> As for putting it in its own dir/package is because I wanted it to have its own package. Not just be `utils.` like everything else. To be honest, I want to just completely change the name `utils`. Not everything can be considered "utilities". Give it proper package names. I'd personally use `src` or `lib`, but I saw Go likes to use `pkg` for the main code folder. Then use subfolders for any files so they can have packages that actually correspond to what they are.
> 
> ```
> pkg
>   |--convert
>   |   |--db.go
>   |--logging
>       |--logging.go
>   |--utils
>       |--validator.go
> ```
> 
> Even `validator.go` could have a proper package name but I couldn't think of one right now. Generally, you want to avoid having a bunch of `utils` functions. Try to find a proper name or place for them. Otherwise it becomes a loose collection of things that have nothing in common.

For logging, I was thinking of doing something similar to what I did for Postgres/MySQL detection in `Convert` (just doing a switch over the levels ex: "low", "medium", "high"), but honestly, an unsigned int `Log` field is probably easier, and more manageable than an Enum IMO. 

In terms of rearranging utils, I agree 100%, just want to minimize overhead as much as possible but that shouldn't be an issue anyway. Also, for the `Convert` function, I'd prefer it be a method of `Config` because there's lots of parameter repetition and "DRY-violations" across the codebase; it's getting to the point where there are like 20+ chars running offscreen because of it.

**Comment by cappe987** [comment]
Ended up having to do some re-organizing to use the `Config` struct in `Convert`. And while at it I decided to do a bit more organizing of code. 

I changed logging to just use `uint32` for level. Also added logging options to the config.

**Review by DGKSK8LIFE — APPROVED** [review]
I will merge once this is integrated with pipelining. I will have to examine this more deeply pre-merge. Also for logging levels, it's best to use `uint8` because we don't need a higher range than that.

**Review by DGKSK8LIFE — COMMENTED** [review]
Looks good overall, please change the docs in `README.md` to reflect config changes. Also, I think we should figure out an algorithm to generate the optimal chunk size based on row count but that can be done later.

**Pull request merged**
